FROM golang:1.10-alpine

COPY . /go/src/github.com/jasontthai/tinyalias
WORKDIR /go/src/github.com/jasontthai/tinyalias

RUN go install ./cmd/url-shortener-worker

RUN adduser -D myuser
USER myuser

CMD /go/bin/url-shortener-worker